apiVersion: v2
name: csi-driver-smb
description: SMB CSI Driver for mounting SMB shares in Kubernetes
type: application
version: 0.1.0
appVersion: "v1.18.0"

dependencies:
  - name: csi-driver-smb
    version: 1.20.1
    repository: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
