{{- if and .Values.storage.enabled (not .Values.storage.hostPath) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ollama.fullname" . }}-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ollama.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  {{- if .Values.storage.storageClass }}
  storageClassName: {{ .Values.storage.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
{{- end }}
