{{- if .Values.vault.enabled }}
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: KubernetesAuthEngineRole
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "harbor-local.labels" . | nindent 4 }}
spec:
  connection:
    address: {{ .Values.vault.address }}
    {{- if .Values.vault.skipTLSVerify }}
    tLSConfig:
      skipVerify: true
    {{- end }}
  authentication:
    path: {{ .Values.vault.kubernetes.mountPath }}
    role: vault-config-operator
  path: {{ .Values.vault.kubernetes.mountPath }}
  name: {{ .Values.vault.kubernetes.role }}
  targetServiceAccounts:
    - {{ .Values.vault.kubernetes.serviceAccount }}
  targetNamespaces:
    targetNamespaces:
      - {{ .Release.Namespace }}
  policies:
    - {{ .Release.Name }}
  audience: {{ .Values.vault.kubernetes.audience }}
  tokenTTL: {{ .Values.vault.kubernetes.tokenTTL | default 86400 }}
{{- end }}
