apiVersion: v1
kind: Service
metadata:
  name: {{ include "haystack.fullname" . }}-hayhooks
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "haystack.hayhooksLabels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: api
    port: {{ .Values.service.apiPort }}
    targetPort: api
    protocol: TCP
  - name: mcp
    port: {{ .Values.service.mcpPort }}
    targetPort: mcp
    protocol: TCP
  selector:
    {{- include "haystack.hayhooksSelectorLabels" . | nindent 4 }}
