{{- if .Values.vault.enabled }}
# GitHub Token for cloning private repositories
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ include "haystack.fullname" . }}-github
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "haystack.labels" . | nindent 4 }}
spec:
  vaultAuthRef: {{ include "haystack.fullname" . }}-auth
  mount: {{ .Values.vault.mount }}
  type: kv-v2
  path: {{ .Values.vault.secrets.github }}
  refreshAfter: 1h
  destination:
    name: {{ include "haystack.fullname" . }}-github
    create: true
{{- end }}
