
apiVersion: v2
name: argocd
description: A wrapper chart for ArgoCD
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.1.0

dependencies:
  - name: argo-cd
    alias: argocd
    version: "9.5.4"
    repository: "https://argoproj.github.io/argo-helm"
