apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ .Values.smb.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  vaultAuthRef: {{ .Release.Name }}-auth
  mount: {{ .Values.vault.mount }}
  type: kv-v2
  path: {{ .Values.smb.vaultPath }}
  refreshAfter: {{ .Values.vault.refreshAfter }}
  destination:
    create: true
    name: {{ .Values.smb.secretName }}
