{{- if .Values.vault.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.vault.kubernetes.serviceAccount }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "companion.labels" . | nindent 4 }}
{{- end }}
