{{- if and .Values.vault.enabled .Values.vault.secrets }}
{{- range $key, $path := .Values.vault.secrets }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ include "companion.fullname" $ }}-{{ $key }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "companion.labels" $ | nindent 4 }}
spec:
  vaultAuthRef: {{ include "companion.fullname" $ }}-auth
  mount: {{ $.Values.vault.mount }}
  type: kv-v2
  path: {{ $path }}
  refreshAfter: {{ $.Values.vault.refreshAfter }}
  destination:
    name: {{ include "companion.fullname" $ }}-{{ $key }}
    create: true
{{- end }}
{{- end }}
