{
 "title": "Arris Surfboard SB8200",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Ping",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(probe_icmp_duration_seconds{job=\"blackbox-ping\", phase=\"rtt\"}) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "(probe_icmp_duration_seconds{job=\"blackbox-ping\", phase=\"rtt\", instance=\"8.8.8.8\"} == 0)+.05",
     "legendFormat": "outage"
    }
   ]
  },
  {
   "title": "Downstream SNR",
   "type": "timeseries",
   "description": "# Downstream SNR\n[ARRIS Consumer Care](https://arris.secure.force.com/consumers/articles/General_FAQs/SB8200-Cable-Signal-Levels/?l=en_US&fs=RelatedArticle):\n\nAcceptable Downstream SNR Levels (dB):\n- If QAM256 and DPL( -6 dBmV to +15 dBmV) SNR should be 30 dB or greater.\n- If QAM256 and DPL(-15 dBmV to -6 dBmV) SNR should be 33 dB or greater.\n\n# Signal to Noise Ratio\n[Wolf Paulus - Cable Modem Signal Levels](https://wolfpaulus.com/hardware/cablemodem/):\n> The downstream SNR tells how much noise is on the cable. Again, for the cable modem to work within the specification, the SNR needs to be at least 23.5dB; a desirable ratio is 30 dB or higher.\n",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "expr": "sum(sb8200_downstream_snr_db{downstream !~ \"0|10\" }) by (downstream)",
     "legendFormat": "{{downstream}}"
    }
   ]
  },
  {
   "title": "Downstream Received Power",
   "type": "timeseries",
   "description": "# Downstream Power Levels\n[ARRIS Consumer Care](https://arris.secure.force.com/consumers/articles/General_FAQs/SB8200-Cable-Signal-Levels/?l=en_US&fs=RelatedArticle):\n\nAcceptable Downstream SNR Levels (dB):\n- If QAM256 and DPL( -6 dBmV to +15 dBmV) SNR should be 30 dB or greater.\n- If QAM256 and DPL(-15 dBmV to -6 dBmV) SNR should be 33 dB or greater.\n",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "sum(sb8200_downstream_power_dbmv) by (downstream)",
     "legendFormat": "{{downstream}}"
    }
   ]
  },
  {
   "title": "Downstream: Rate of Corrected and Uncorrectable Packet Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(sb8200_dowmstream_correcteds_total{downstream != \"48\"}[10m])",
     "legendFormat": "corrected@ch{{downstream}}"
    },
    {
     "expr": "rate(sb8200_downstream_uncorrectables_total{downstream != \"48\"}[10m])",
     "legendFormat": "uncorrectable@ch{{downstream}}"
    }
   ]
  },
  {
   "title": "Upstream Transmit Power",
   "type": "timeseries",
   "description": "# Upstream Power Levels\n[ARRIS Consumer Care](https://arris.secure.force.com/consumers/articles/General_FAQs/SB8200-Cable-Signal-Levels/?l=en_US&fs=RelatedArticle):\n\nAcceptable Upstream Power Levels (dBmV)\n- Three or more\tSC-QAM\t45 dBmV to 51 dBmV\n\n",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "sum(sb8200_upstream_power_dbmv) by (upstream)",
     "legendFormat": "channel {{channel_id}}"
    }
   ]
  },
  {
   "title": "Downstream Frequency (Hz)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    { "expr": "sb8200_downstrem_freq_hertz", "legendFormat": "{{downstream}}" }
   ]
  },
  {
   "title": "Upstream Frequency (Hz)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    { "expr": "sb8200_upstream_freq_hertz", "legendFormat": "{{upstream}}" }
   ]
  },
  {
   "title": "Downstream Modulation (QAM)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sb8200_downstream_modulation_qam",
     "legendFormat": "{{downstream}}"
    }
   ]
  },
  {
   "title": "Upstream Channel Width (Hz)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    { "expr": "sb8200_upstream_width_hertz", "legendFormat": "{{upstream}}" }
   ]
  },
  {
   "title": "Down stream channel count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "count(changes(sb8200_downstream_snr_db[30m]) != 0)",
     "legendFormat": "channel count"
    }
   ]
  }
 ]
}