{{- if ((.Values.serviceAccount).create) | default false }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "simple-service.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "simple-service.labels" . | nindent 4 }}
  {{- with (.Values.serviceAccount).annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ ((.Values.serviceAccount).automountServiceAccountToken) | default false }}
{{- end }}
