{{- if and .Values.vault.enabled .Values.vault.secrets }}
apiVersion: redhatcop.redhat.io/v1alpha1
kind: KubernetesAuthEngineRole
metadata:
  name: {{ include "simple-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "simple-service.labels" . | nindent 4 }}
spec:
  connection:
    address: {{ .Values.vault.address }}
    {{- if .Values.vault.skipTLSVerify }}
    tLSConfig:
      skipVerify: true
    {{- end }}
  authentication:
    path: {{ .Values.vault.kubernetes.mountPath }}
    role: vault-config-operator
  path: {{ .Values.vault.kubernetes.mountPath }}
  name: {{ .Values.vault.kubernetes.role | default .Release.Name }}
  targetServiceAccounts:
    - {{ .Values.vault.kubernetes.serviceAccount | default (include "simple-service.serviceAccountName" .) }}
  targetNamespaces:
    targetNamespaces:
      - {{ .Release.Namespace }}
  policies:
    - {{ include "simple-service.fullname" . }}
  audience: {{ .Values.vault.kubernetes.audience }}
  tokenTTL: {{ .Values.vault.kubernetes.tokenTTL | default 86400 }}
{{- end }}
