{{- if .Values.vault.enabled }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: {{ include "simple-service.fullname" . }}-connection
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "simple-service.labels" . | nindent 4 }}
spec:
  address: {{ .Values.vault.address }}
  skipTLSVerify: {{ .Values.vault.skipTLSVerify }}
{{- end }}
